
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON FIELD KEYWORD PHRASE QUOTES SPACEquery : expression SPACE query\n                 | expressionexpression : FIELD COLON value\n                      | valuevalue : PHRASE\n                 | KEYWORD'
    
_lr_action_items = {'FIELD':([0,7,],[3,3,]),'PHRASE':([0,7,8,],[5,5,5,]),'KEYWORD':([0,7,8,],[6,6,6,]),'$end':([1,2,4,5,6,9,10,],[0,-2,-4,-5,-6,-1,-3,]),'SPACE':([2,4,5,6,10,],[7,-4,-5,-6,-3,]),'COLON':([3,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,7,],[1,9,]),'expression':([0,7,],[2,2,]),'value':([0,7,8,],[4,4,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> expression SPACE query','query',3,'p_query','es_API.py',89),
  ('query -> expression','query',1,'p_query','es_API.py',90),
  ('expression -> FIELD COLON value','expression',3,'p_expression','es_API.py',99),
  ('expression -> value','expression',1,'p_expression','es_API.py',100),
  ('value -> PHRASE','value',1,'p_value','es_API.py',135),
  ('value -> KEYWORD','value',1,'p_value','es_API.py',136),
]
