
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON FIELD KEYWORD PHRASE QUOTESquery : expression\n                 | query expressionexpression : FIELD COLON value\n                      | valuevalue : PHRASE\n                 | KEYWORDphrase : KEYWORD\n                 | KEYWORD KEYWORD'
    
_lr_action_items = {'FIELD':([0,1,2,4,5,6,7,9,],[3,3,-1,-4,-5,-6,-2,-3,]),'PHRASE':([0,1,2,4,5,6,7,8,9,],[5,5,-1,-4,-5,-6,-2,5,-3,]),'KEYWORD':([0,1,2,4,5,6,7,8,9,],[6,6,-1,-4,-5,-6,-2,6,-3,]),'$end':([1,2,4,5,6,7,9,],[0,-1,-4,-5,-6,-2,-3,]),'COLON':([3,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'expression':([0,1,],[2,7,]),'value':([0,1,8,],[4,4,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> expression','query',1,'p_query','es_API.py',65),
  ('query -> query expression','query',2,'p_query','es_API.py',66),
  ('expression -> FIELD COLON value','expression',3,'p_expression','es_API.py',75),
  ('expression -> value','expression',1,'p_expression','es_API.py',76),
  ('value -> PHRASE','value',1,'p_value','es_API.py',127),
  ('value -> KEYWORD','value',1,'p_value','es_API.py',128),
  ('phrase -> KEYWORD','phrase',1,'p_phrase','es_API.py',135),
  ('phrase -> KEYWORD KEYWORD','phrase',2,'p_phrase','es_API.py',136),
]
